### ISSUE TITLE
provide services to choose language and locale

### ISSUE THREAD

**Issue by rpenny125** [zowe/zlux-app-manager#10]
By default, the translation schemes should pick up the language from the browser. However, a user should be able to pick a language without having to restart their browser.

It's suggested that the this could be managed through the use of a cookie. This way we don't have to worry about the chicken and egg problem of remembering a language choice in the server and figuring out how to apply this choice during login.

The UI for choosing the language must offer "Browser Language" as an option (which would be the default), so that users can put their language choice back in the hands of the browser.

The exact UI for users to specify a language will come later.

It is acceptable that the application has to be reloaded.

### Proposal

1. Language and Locale preferences will be "per browser"
  a. Simplifies QA, and allows all users to "compare languages" by using, for example, Firefox and Chrome
2. Use cookies
  a. It's available before login, so login dialog can have correct language
  b. server might prefer to know the language of the client
  c. It's a small amount of data, so size/performance impact on browser is minimal

### Specifics

1. Separate cookies for language and local (allow people to specify Mexican Spanish, even if they live in the US)
2. Persistent
3. Visible to javascript
4. site-wide
5. Age: as long as possible (no expiration? or 100 years from now)

### Supporting Documentation
Why give the user explicit control rather than rely on the browser:
https://www.w3.org/International/questions/qa-accept-lang-locales

**Comment by 1000TurquoisePogs** [comment]
Is this done? I think this code was already merged.
